---
title: "Plot Palmer Penguins"
author: 
    name: "Monique Hernandez"
    affiliation: University of California, Santa Barbara
date: "Augustt 18, 2026"
format:
  html:
    toc: true
execute:
  message: false
  warning: false
---
[click here for github link](https://github.com/moniqueallyson/eds221day6) 

## Setup

```{r, message=FALSE}
library(tidyverse)
library(palmerpenguins)
```

```{r, fig.show='hide'}
ggplot(data = penguins) # plot penguin data
```

## ggplot
```{r, out.width="50%", fig.align="center"}
ggplot(
  data = penguins, #. data
  mapping = aes(
    x = flipper_length_mm, # x-axis by flipper length in mm
    y = body_mass_g # y-axis by body mass in grams
  )
)
```

## Geometry
```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = flipper_length_mm,
    y = body_mass_g
  )
) +
  geom_point()
```

## Types of Plots
```{r}
ggplot(
  data = penguins,
  mapping = aes(x = island)
) +
  geom_bar() # bar chart

ggplot(
  data = penguins,
  mapping = aes(x = body_mass_g)
) + geom_histogram() # histogram

```

## Boxplot

```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = species,
    y = body_mass_g
  )
) +
  geom_boxplot()

# X and Y are not our only aesthetics
ggplot(
  data = penguins,
  mapping = aes(
    x = species,
    y = body_mass_g,
    fill = species
  )
) +
  geom_boxplot()


ggplot(
  data = penguins,
  mapping = aes(
    x = species,
    y = body_mass_g,
    fill = island  # What if fill and x refer to different columns
  )
) +
  geom_boxplot()
```


# **Scales** control how mapping appear

```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = species,
   y = body_mass_g,
    fill = island
  )
) +
  geom_boxplot() +
  scale_y_continuous(
    name = "Body mass (g)",
    limits = c(2000, 7000)
)

# The shape aesthetic works on scatters
ggplot(
  data = penguins,
  mapping = aes(
    x = body_mass_g,
    y = flipper_length_mm,
    shape = species,
    color = species
  )
) +
  geom_point() +
  scale_shape_manual(
  values = c(
    Adelie = "square",
    Chinstrap = "diamond",
    Gentoo = "circle"
  )
)
```



