---
title: "Palmer Penguins"
author: 
    name: "Monique Hernandez"
    affiliation: University of California, Santa Barbara
date: "Augustt 18, 2026"
format:
  html:
    toc: true
execute:
  message: false
  warning: false
---

## Setup

```{r}
library(tidyverse)  # load `library()` function

library(palmerpenguins) # pakages contain functions and data
penguins
glimpse(penguins) # glimpse() rotates the printing of a data frame so you can see every column
```

::: {.callout-tip}
## Tip
Command K, then press H to input "rows" or "columns"
:::

# rows -------------------------------------------------------------------

## Filter
```{r}

# Keeps rows that satisfy one or more conditions
filter(penguins, sex == "female")
# arguments separated by commas -- two arguments above^
# Can the data frame be an argument? Everything in R can be an argument

# this gives 300+ rows and says True or False if [penguins$sex == "female"]

filter(penguins, species == "chinstrap")
# What about this?
filter(penguins, species == "female") # This is a data frame with 0's
# Returns a data frame ALWAY

filter(penguins, body_mass_g < 3000)

# What about | ?
filter(penguins, sex == "female" | flipper_length_mm > 190)
# |, & are the _vectorized_ versions of ||, &&
# Save the doubles for if(), use the singles in data frames
```

## Arrange
```{r}
## Arrange

# arrange() sorts rows by one or more columns

arrange(penguins, bill_depth_mm)
arrange(penguins, island)
# Can sort by multiple columns (order matter!!)
arrange(penguins, island, bill_depth_mm)

# What if I want descending order?
arrange(penguins, desc(body_mass_g))
```

## Distinct and Count
```{r}

## Distinct and Count
distinct(penguins, island)
count(penguins, island)
# Works on multiple columns too
count(penguins, species, island)

```

# columns ----------------------------------------------------------------

## Mutate

```{r}
# Adds (or replaces/modifies) columns

mutate(penguins, body_mass_kg = body_mass_g / 1000)

## Select

# Chooses clumns to retain (or exclude)
select(penguins, body_mass_g)
penguins_kg_g <- mutate(penguins, body_mass_kg = body_mass_g / 1000)
select(penguins_kg_g, body_mass_kg, body_mass_g)

# Mutate can create more than one column at a time
mutate(
  penguins,
  body_mass_kg = body_mass_g / 1000,
  bill_length_cm = bill_length_mm / 10
)

# Relocate columns using .before

mutate(
  penguins,
  body_mass_kg = body_mass_g / 1000,
  bill_length_cm = bill_length_mm / 10,
  .before = 1
)

```

```{r}
# Helpers for select
# : select ranges of columns
# ! excludes columns
select(penguins, species:island)
select(penguins, species:bill_depth_mm)
select(penguins, !species)
select(penguins, !island:bill_length_mm)

# Select() family of helper functions
select(penguins, starts_with("bill"))
select(penguins, ends_with("mm"))
select(penguins, contains("length"))
```


# pipe -------------------------------------------------------------------

```{r}
# Chaining together multiple functions is ugly
filter(mutate(penguins, body_mass_kg = body_mass_g / 1000), body_mass_kg < 2.8)
filter(
  mutate(
    penguins,
    body_mass_kg = body_mass_g / 1000
  ),
  body_mass_kg < 2.8
)
# Command shift P -> initliaze workspace folder press yes --- for clean indents in above^

# Pipe to the rescue
# Command shift m
penguins |>
  mutate(body_mass_kg = body_mass_g / 1000) |>
  filter(body_mass_g < 2.8)

# My turn - yay!
# Flip this into the correct order using pipes
select(arrange(penguins, species, bill_length_mm), species:bill_length_mm)

# Answer
penguins |>
  arrange(penguins, species, bill_length_mm) |>
  select(species:bill_length_mm)
```


# Summarize --------------------------------------------------------------

```{r}
penguins |>
  summarize(avg_size = mean(body_mass_g))
# NA is R's way of representing missing data
penguins |>
  summarize(avg_size = mean(body_mass_g, na.rm = TRUE))

# By default, summaries happen across the entire data frame (typically we want by groups like species)
# Use .by to group
penguins |>
  summarize(avg_size = mean(body_mass_g, na.rm = TRUE), .by = species)

# Grouping by multiple columns
penguins |>
  summarize(
    avg_size = mean(body_mass_g, na.rm = TRUE),
    .by = c(species, island)
  )

# Creating multiple summaries
penguins |>
  summarize(
    avg_size = mean(body_mass_g, na.rm = TRUE),
    n_penguins = n(),
    .by = c(species, island)
  )

```